name: Deploy Svelte App to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Keep this at v3
        with:
          node-version: '20'  # Specify Node.js version 20

      - name: Install dependencies
        run: npm install

      - name: Build the Svelte app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Ensure this is the latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Adjust if your output directory is different
