# This workflow will build and deploy a Svelte app to GitHub Pages using Node.js version 20

name: Deploy Svelte App

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Check out the repository
      - uses: actions/setup-node@v4  # Set up Node.js environment
        with:
          node-version: 20  # Use Node.js version 20

      - run: npm ci  # Install dependencies with npm ci
      - run: npm run build  # Build the Svelte app

  deploy:
    needs: build  # Ensure the build job completes successfully
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Check out the repository again for deployment
      - uses: actions/setup-node@v4  # Set up Node.js for deployment
        with:
          node-version: 20  # Use Node.js version 20

      - run: npm ci  # Install dependencies again for the deployment
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Deploy the build to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Adjust if your output directory is different
