name: Deploy Svelte App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this action on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Use latest version of checkout

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Use Node.js version 20

      - name: Install dependencies
        run: npm ci  # Use 'npm ci' to install dependencies

      - name: Build the Svelte app
        run: npm run build  # This assumes you have a build script in your package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # This is the default output directory for Svelte builds, adjust if necessary

