name: Build and Deploy Svelte App

on:
  push:
    branches:
      - main  # Build and deploy only when pushing to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js with a specific version
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js version 20

      # Step 3: Install dependencies from package.json
      - name: Install dependencies
        run: npm ci  # Clean install Node.js packages

      # Step 4: Build the Svelte app
      - name: Build Svelte app
        run: npm run build  # Run the build command for your Svelte app

      # Step 5: Deploy the app to GitHub Pages from the root folder
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # GitHub Pages Action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token for authentication
          publish_dir: ./public  # Path where the build output is located
